#!/bin/zsh
# hand-merge.sh <track> <short-sha> <msgfile>: a lane's merge when merge-lane.sh would refuse for conflicts the
# program itself creates (2026-09-20: three lanes retiring boards on adjacent registration lines conflict at every
# merge after the first). One resolver per file kind, then the same proof the merge script demands:
#   registration deletions (sandbox/registry.ts, (shell)/lab/boards.ts): INTERSECTION of both sides of each hunk,
#     so every deletion is kept;
#   rows and notes (touchpoints.ts, rules/component-notes.ts): UNION of both sides (each lane rewrote its own row),
#     then any retired id the union re-added to DESK_ORDER is dropped (the typecheck caught this once);
#   generated files (docs/design/library.md, rules/rules.generated.json): REGENERATED by design:rules, never merged;
#   the lane's manifest deleted (the merge commit that integrates a track deletes its manifest);
# then typecheck and the registry tests on their own exit codes, and the commit with the lane's message. Any other
# conflicted path stops the script with the merge left in progress for a human read. Never a force, never a rebase.
set -u; setopt nonomatch pipefail
TRACK="$1"; SHA="$2"; MSG="$3"; REPO=/Users/gibby/local/ai/partyreel; cd "$REPO"
S=${S:-/private/tmp/claude-501/-Users-gibby-local-ai-partyreel/b97eafa6-025b-4736-847b-48f80c42ec24/scratchpad}
[ -z "$(git status --short)" ] || { echo "REFUSED: tree not clean"; exit 2; }
git fetch -q origin "lp/$TRACK" || { echo "REFUSED: no origin/lp/$TRACK"; exit 2; }
HEAD_SHORT=$(git rev-parse --short "origin/lp/$TRACK"); [ "$HEAD_SHORT" = "$SHA" ] || { echo "REFUSED: lane head is $HEAD_SHORT, not $SHA"; exit 2; }
rm -rf .next/dev
git merge --no-ff --no-commit "origin/lp/$TRACK" >/dev/null 2>&1 || true
CONFL=("${(@f)$(git diff --name-only --diff-filter=U)}"); CONFL=("${(@)CONFL:#}")
echo "conflicted: ${#CONFL[@]} ${CONFL[*]}"
REG="src/app/(dev)/design/sandbox/registry.ts"; BOARDS="src/app/(dev)/design/(shell)/lab/boards.ts"
TP="src/app/(dev)/design/touchpoints.ts"; NOTES="src/app/(dev)/design/rules/component-notes.ts"
LIB="docs/design/library.md"; GEN="src/app/(dev)/design/rules/rules.generated.json"
for f in "${CONFL[@]}"; do
  [ -n "$f" ] || continue
  case "$f" in
    "$REG"|"$BOARDS") python3 - "$f" <<'PY'
import re,sys
p=sys.argv[1]; s=open(p).read()
def keep(m):
    ours=m.group(1).split("\n"); theirs=m.group(2).split("\n"); k=[l for l in ours if l in theirs]
    return ("\n".join(k)+"\n") if k else ""
s2,n=re.subn(r"<<<<<<< [^\n]*\n(.*?)=======\n(.*?)>>>>>>> [^\n]*\n", keep, s, flags=re.S); open(p,"w").write(s2); print(f"intersection: {p} ({n} hunks)")
PY
      ;;
    "$TP"|"$NOTES") git show ":1:$f" > "$S/hm-base"; git show ":2:$f" > "$S/hm-ours"; git show ":3:$f" > "$S/hm-theirs"
      git merge-file --union -p "$S/hm-ours" "$S/hm-base" "$S/hm-theirs" > "$f"; echo "union: $f"
      # A union prints a line both sides END on once: two lanes' head blocks in component-notes.ts both end on
      # "  }," so the first block lost its closer (2026-09-21, app-pricing-wiring). Close any entry whose next key
      # arrives without one; the comment lines above a key belong to that key.
      [ "$f" = "$NOTES" ] && python3 "$KIT/closer.py" "$f"
      ;;
    "$LIB"|"$GEN") echo "regenerate: $f" ;;
    *) echo "STOP: $f conflicts and no resolver owns it; the merge is left in progress"; exit 3 ;;
  esac
done
# retired ids the union re-added (2026-09-21: the union restores the deleted `| "id"` line of the SandboxId type as
# well as the DESK_ORDER entry, so the type is no oracle): the standing set is what registry.ts still imports after
# the intersection, and every other id leaves BOTH the SandboxId union and DESK_ORDER (RulingId keeps it).
python3 - "$TP" "$REG" <<'PY'
import re,sys
tp,reg=sys.argv[1],sys.argv[2]; s=open(tp).read()
standing=set(re.findall(r'from "\./([a-z0-9-]+)/spec"', open(reg).read()))
if not standing: sys.exit("STOP: registry.ts imports no spec")
a=s.index("export type SandboxId"); b=s.index(";", a); u=s[a:b]
gone=[x for x in re.findall(r'"([a-z0-9-]+)"', u) if x not in standing]
for x in gone: u=re.sub(r'^\s*\|\s*"'+x+r'"\s*\n', "", u, flags=re.M)
s=s[:a]+u+s[b:]
i=s.index("export const DESK_ORDER"); j=s.index("];", i); block=s[i:j]
ids=re.findall(r'^\s*"([a-z0-9-]+)",\s*$', block, re.M)
drop=[x for x in ids if x not in standing]
for x in drop: block=re.sub(r'^\s*"'+x+r'",\s*\n', "", block, flags=re.M)
open(tp,"w").write(s[:i]+block+s[j:]); print("SandboxId: dropped", gone or "nothing", "| DESK_ORDER: dropped", drop or "nothing")
PY
grep -l "<<<<<<<" "$REG" "$BOARDS" "$TP" "$NOTES" 2>/dev/null && { echo "STOP: markers remain"; exit 3; }
pnpm -s design:rules >/dev/null 2>&1 || { echo "STOP: design:rules failed"; exit 3; }
[ -f "docs/tracks/$TRACK.md" ] && git rm -qf "docs/tracks/$TRACK.md"
git add "$REG" "$BOARDS" "$TP" "$NOTES" "$LIB" "$GEN" 2>/dev/null
pnpm -s typecheck > "$S/$TRACK-typecheck.log" 2>&1; TC=$?
pnpm -s vitest run "src/app/(dev)/design/touchpoints.test.ts" "src/app/(dev)/design/sandbox/registry.test.ts" "src/app/(dev)/design/rules/rules-registry.test.ts" "src/app/(dev)/design/(shell)/lab/_desk/queue.test.ts" src/lib/track-manifests.test.ts > "$S/$TRACK-registry-tests.log" 2>&1; RT=$?
echo "typecheck $TC registry-tests $RT"
[ "$TC" = 0 ] && [ "$RT" = 0 ] || { echo "RED before commit; merge left staged"; grep -E "error TS" "$S/$TRACK-typecheck.log" | head -5; grep -E "FAIL|×" "$S/$TRACK-registry-tests.log" | head -5; exit 1; }
git commit -q -F "$MSG" || { echo "STOP: commit failed"; exit 1; }
python3 - <<'PY'
import re
s=open("src/app/(dev)/design/touchpoints.ts").read(); i=s.index("export const DESK_ORDER"); j=s.index("];",i)
print("desk boards:", len(re.findall(r'^\s*"[a-z0-9-]+",\s*$', s[i:j], re.M)))
PY
echo "MERGED $(git rev-parse --short HEAD)"
