/**
 * THE HOST HUB'S ETAG (Will, `first=live`, 2026-09-21: "It lands while she is
 * looking").
 *
 * The guest's `gallery-fingerprint.ts` is the SHAPE this copies, deliberately
 * not the module it reuses: that hash is ACCESS-shaped — it carries the access
 * level and the teaser total precisely so a teaser viewer's ETag can never
 * validate a full payload. A host has one access level to their own event and
 * needs the two facts a guest is never told: what is in the album, and how much
 * is waiting in Review. Folding those into the guest's hash would put host-only
 * state inside a validator handed to anonymous guests.
 *
 * WHAT IS IN IT, AND WHY EACH:
 *  - the EVENT ID, so a validator can never cross events. RLS already refuses a
 *    foreign event, but an ETag that matched across two of a host's own events
 *    would 304 a stale album into the wrong page.
 *  - every visible item's id AND status, so a hide or an unhide from a second
 *    tab reaches this one. Status is the only field on a visible row that
 *    changes after creation; everything else is write-once at create_media.
 *  - the PENDING COUNT, which is the whole reason this poll exists beside the
 *    doorbell. The `media_gallery_doorbell` trigger fires only when the
 *    APPROVED-VISIBLE set changes (migration 20260611220000, lines 28-45), so a
 *    held upload arriving on a moderated event wakes nobody. The host is the one
 *    person who has to hear about it.
 *
 * DELIBERATELY OUTSIDE THE HASH: presigned URLs. They roll about every 30
 * minutes and are regenerated by the page render this validator triggers, never
 * by this route — hashing them would make the hub refresh itself on a clock,
 * which is exactly what `first=live` rules out (the hub is eleven queries plus
 * three presigns an item; a timed refresh would be the most expensive poll in
 * the product).
 *
 * Pure module (node:crypto only), so the rules are Vitest-pinnable.
 */
import { createHash } from "node:crypto";

export type HostFingerprintItem = {
  id: string;
  /** 'approved' | 'hidden' — the two states a VISIBLE row can be in. */
  status: string | null;
};

export function hostEtag(input: {
  eventId: string;
  pending: number;
  items: HostFingerprintItem[];
}): string {
  // Canonical array form (not objects) so key order can never wobble the hash.
  const canonical = JSON.stringify([
    input.eventId,
    input.pending,
    input.items.map((i) => [i.id, i.status ?? ""]),
  ]);
  const hash = createHash("sha256")
    .update(canonical)
    .digest("base64url")
    .slice(0, 27);
  // Strong, quoted, version-prefixed: a future shape change bumps h1 -> h2 so
  // clients holding an old validator can never false-match.
  return `"h1-${hash}"`;
}
