/**
 * THE HOST HUB'S ETAG (Will, `first=live`, 2026-09-21: "It lands while she is
 * looking").
 *
 * The guest's `gallery-fingerprint.ts` is the SHAPE this copies, deliberately
 * not the module it reuses: that hash is ACCESS-shaped — it carries the access
 * level and the teaser total precisely so a teaser viewer's ETag can never
 * validate a full payload. A host has one access level to their own event and
 * needs the two facts a guest is never told: what is in the album, and how much
 * is waiting in Review. Folding those into the guest's hash would put host-only
 * state inside a validator handed to anonymous guests.
 *
 * WHAT IS IN IT, AND WHY EACH:
 *  - the EVENT ID, so a validator can never cross events. RLS already refuses a
 *    foreign event, but an ETag that matched across two of a host's own events
 *    would 304 a stale album into the wrong page.
 *  - the ALBUM COUNT (approved + hidden), so an arrival or a removal reaches the
 *    page, and the PENDING COUNT, which is the whole reason this poll exists
 *    beside the doorbell. The `media_gallery_doorbell` trigger fires only when the
 *    APPROVED-VISIBLE set changes (migration 20260611220000, lines 28-45), so a
 *    held upload arriving on a moderated event wakes nobody. The host is the one
 *    person who has to hear about it.
 *  - the NEWEST `updated_at` among the event's non-removed media, so a hide or
 *    an unhide from a second tab reaches this one though neither count moves:
 *    `media_set_updated_at` stamps every write to a row, a status flip included.
 *    Two changes that cancel in the counts (one arrival, one removal) still move
 *    it, because the arrival is the newest write.
 *
 * ★ THREE NUMBERS, NOT A LIST (the 1,000-row round, 2026-09-23). A hash of the
 * item list would read it in one select, which PostgREST ends at 1,000 rows, so
 * an album's oldest photographs could change without the hash ever seeing it.
 * Head counts and a one-row read cost the same at 50 items and at 50,000.
 *
 * DELIBERATELY OUTSIDE THE HASH: presigned URLs. They roll about every 30
 * minutes and are regenerated by the page render this validator triggers, never
 * by this route — hashing them would make the hub refresh itself on a clock,
 * which is exactly what `first=live` rules out (the hub is eleven queries plus
 * three presigns an item; a timed refresh would be the most expensive poll in
 * the product).
 *
 * Pure module (node:crypto only), so the rules are Vitest-pinnable.
 */
import { createHash } from "node:crypto";

export type HostFingerprint = {
  eventId: string;
  /** Approved + hidden: the album's own count. */
  album: number;
  /** Waiting in Review. */
  pending: number;
  /** The newest `updated_at` among the event's non-removed media; null for an empty event. */
  newestUpdatedAt: string | null;
};

export function hostEtag(input: HostFingerprint): string {
  // Canonical array form (not objects) so key order can never wobble the hash.
  const canonical = JSON.stringify([
    input.eventId,
    input.album,
    input.pending,
    input.newestUpdatedAt ?? "",
  ]);
  const hash = createHash("sha256")
    .update(canonical)
    .digest("base64url")
    .slice(0, 27);
  // Strong, quoted, version-prefixed: a shape change bumps the prefix (h1 hashed the item list,
  // h2 hashes the counts) so a client holding an old validator can never false-match.
  return `"h2-${hash}"`;
}
