"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { CalendarPlus } from "lucide-react";
import { toast } from "sonner";

import { createEventAction } from "@/app/(app)/dashboard/actions";
import {
  createEventSchema,
  type CreateEventInput,
  type CreateEventValues,
} from "@/lib/validation/event";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type CreateEventDialogProps = {
  atCap: boolean;
  planName: string;
};

// WHY this is the ONLY field set at creation: the PRD wants the lowest-friction
// path to a shareable QR. Everything else (visibility, moderation, the toggles)
// lives on the event page and defaults sensibly at the DB layer. qr_token /
// share_token are generated by DB defaults — the client never sends them.
export function CreateEventDialog({ atCap, planName }: CreateEventDialogProps) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [isPending, startTransition] = useTransition();

  // Form input ≠ output: createEventSchema carries .default()s, so the resolved
  // (output) type marks them required while the form still starts from inputs.
  const form = useForm<CreateEventInput, unknown, CreateEventValues>({
    resolver: zodResolver(createEventSchema),
    defaultValues: { name: "", description: "", event_date: "" },
  });

  function onSubmit(values: CreateEventValues) {
    startTransition(async () => {
      const result = await createEventAction(values);
      // On success the action redirects to /dashboard/[id]; nothing resolves
      // here. We only land past this point when it returns a failure result.
      if (!result || result.ok) return;

      if (result.code === "limit_reached") {
        toast.error(`Event limit reached on the ${planName} plan.`, {
          description: "Delete an event or upgrade to add more.",
          action: { label: "Upgrade", onClick: () => router.push("/pricing") },
        });
        return;
      }

      toast.error("Couldn't create the event.", {
        description: result.message,
      });
    });
  }

  // At the tier cap the trigger is inert — the dashboard renders the upgrade
  // hint alongside it, so here we just show why the action is unavailable.
  if (atCap) {
    return (
      <Button disabled>
        <CalendarPlus /> New event
      </Button>
    );
  }

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        setOpen(next);
        if (!next) form.reset();
      }}
    >
      <DialogTrigger asChild>
        <Button>
          <CalendarPlus /> New event
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Create an event</DialogTitle>
          <DialogDescription>
            Name it now — you can fine-tune everything else once it&rsquo;s
            created.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form
            id="create-event-form"
            onSubmit={form.handleSubmit(onSubmit)}
            className="grid gap-4"
          >
            <FormField
              control={form.control}
              name="name"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Event name</FormLabel>
                  <FormControl>
                    <Input
                      autoFocus
                      placeholder="Maya & Sam's Wedding"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="description"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>
                    Description{" "}
                    <span className="font-normal text-muted-foreground">
                      (optional)
                    </span>
                  </FormLabel>
                  <FormControl>
                    <Textarea
                      rows={3}
                      placeholder="A note your guests will see when they join."
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="event_date"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>
                    Event date{" "}
                    <span className="font-normal text-muted-foreground">
                      (optional)
                    </span>
                  </FormLabel>
                  <FormControl>
                    <Input type="date" {...field} />
                  </FormControl>
                  <FormDescription>
                    Just for your reference — events never expire.
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />
          </form>
        </Form>
        <DialogFooter>
          <Button type="submit" form="create-event-form" disabled={isPending}>
            {isPending ? "Creating…" : "Create event"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
