import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { colorPalettes } from "@/components/vendor/border-beam/styles";

// Guards for the VENDORED border-beam package (src/components/vendor/border-beam).
//
// It is copied in verbatim under MIT with a standing instruction not to restyle
// it, which is a contract nothing else in the repo enforces: prettier and eslint
// are both told to leave the folder alone, so a stray edit there would sail
// through the gate. These pins are what is left.
//
// Three hand-ports of this effect were attempted before vendoring, and every one
// missed the same way: our low-chroma five substituted into a palette tuned at
// the sRGB gamut edge, then compensated with filters. The A/B in doctrine
// section 04 exists to settle that by looking, and it is only a fair comparison
// while the two palettes differ in colour and NOTHING else.

const DIR = join(process.cwd(), "src/components/vendor/border-beam");

describe("the vendored border-beam package", () => {
  it("keeps the MIT notice in every source file", () => {
    // MIT requires the copyright notice to survive in copies of the source.
    // User-facing credit is a separate thing and belongs on the attributions
    // page; this is the licence obligation, and it is not optional.
    const files = readdirSync(DIR).filter((f) => /\.tsx?$/.test(f));
    expect(files.length).toBeGreaterThanOrEqual(5);
    for (const f of files) {
      const src = readFileSync(join(DIR, f), "utf8");
      expect(src, `${f} lost its licence header`).toContain("MIT License");
      expect(src, `${f} lost its attribution`).toContain("Jakub Antalik");
    }
  });

  it("marks every deviation from upstream, and has only the two", () => {
    // The value of vendoring is that this IS upstream, so any edit has to
    // announce itself. Two are expected: the "use client" directive Next 16
    // needs, and the extra palette. If a third appears, either it is marked and
    // this number moves deliberately, or someone restyled the package.
    const marks = readdirSync(DIR)
      .filter((f) => /\.tsx?$/.test(f))
      .flatMap((f) =>
        [...readFileSync(join(DIR, f), "utf8").matchAll(/PARTYREEL:/g)].map(
          () => f,
        ),
      );
    // Each of the five files carries the header, which names both deviations.
    const inBody = marks.filter((f) => f !== "index.ts");
    expect(inBody.length).toBeGreaterThanOrEqual(2);
  });

  it("varies only colour between the two palettes under test", () => {
    // The whole point of the section 04 comparison. If a position or a size
    // drifts, the columns stop being the same effect in two palettes and start
    // being two effects, and the ruling made from them is worthless.
    const theirs = colorPalettes.colorful.border;
    const ours = colorPalettes.partyreel.border;

    expect(ours).toHaveLength(theirs.length);
    ours.forEach((lobe, i) => {
      expect(lobe.pos, `lobe ${i} moved`).toBe(theirs[i].pos);
      expect(lobe.size, `lobe ${i} resized`).toBe(theirs[i].size);
      expect(lobe.color, `lobe ${i} is not ours`).not.toBe(theirs[i].color);
    });
  });

  it("ships our hues at a chroma this effect can actually show", () => {
    // Our ratified five sit at oklch chroma 0.14 to 0.17 because the chrome is
    // achromatic everywhere else and the media is the colour. Dropped into
    // gradients tuned at the gamut edge they wash out, which is exactly what
    // sank the hand-ports. These were generated by oklchToSrgb at effect-grade
    // chroma; the pin is that at least one channel is at or near the rail, so
    // a future "let us just use the token values" edit fails here.
    const chan = colorPalettes.partyreel.border.map((l) => {
      const [r, g, b] = l.color.match(/\d+/g)!.map(Number);
      return Math.max(r, g, b) - Math.min(r, g, b);
    });
    for (const spread of chan) expect(spread).toBeGreaterThan(150);
  });
});
