/**
 * The backend-job heartbeat store (admin-portal P8, QA #15) — every read and write of `job_runs`
 * plus the per-job kill-switch rows in `ops_flags`. Both tables are deny-all, so everything here
 * goes through the service-role admin client; the callers are the jobs themselves, the internal
 * job-run endpoint, and the requireAdmin + AAL2 gated /admin/jobs page.
 *
 * Reads and writes share one file on purpose: the heartbeat is a single small protocol (open a row,
 * close it), and splitting it across `queries/` and `mutations/` would put four lines of insert in
 * its own module away from the reads that interpret them. The job vocabulary itself lives in the
 * pure catalog (`src/app/admin/jobs/catalog.ts`).
 *
 * TWO RULES, and they point in opposite directions on purpose:
 *
 *  - The heartbeat WRITES degrade. A job must never fail because its bookkeeping failed, and this
 *    branch ships BEFORE its migration is applied (the Orchestrator applies it), so the very first
 *    deploy would otherwise 500 the purge cron on an unknown table. So the writes swallow and REPORT
 *    (`heartbeatError`), and the caller raises the Sentry warning — Sentry never gets imported into
 *    `src/lib/db/*`.
 *  - The health READS do not. A failed read of a health signal resolves as a confident "nothing to
 *    report", which is the one answer that means "all clear" (see must-query.ts). They use mustQuery
 *    and throw; /admin/jobs catches and says so in the UI instead of drawing an empty, healthy page.
 */
import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";

import { JOBS, type JobId, type JobRunSummary } from "@/app/admin/jobs/catalog";
import { mustQuery } from "@/lib/db/must-query";
import type { Json } from "@/lib/db/types";
import { createAdminClient } from "@/lib/supabase/admin";

export type JobRunStatus = "running" | "ok" | "error" | "skipped";
export type JobTrigger = "schedule" | "manual";

export type JobRunRow = {
  id: string;
  job: string;
  status: JobRunStatus;
  triggered_by: string;
  started_at: string;
  finished_at: string | null;
  duration_ms: number | null;
  counts: Json | null;
  note: string | null;
};

type JobRunInsert = {
  id?: string;
  job: string;
  status: JobRunStatus;
  triggered_by?: string;
  started_at?: string;
  finished_at?: string | null;
  duration_ms?: number | null;
  counts?: Json | null;
  note?: string | null;
};

/**
 * `job_runs` ships in THIS track's migration, and `src/lib/db/types.ts` is regenerated by the
 * Orchestrator only AFTER the migration is applied — so the generated `Database` type cannot know
 * the table yet, and `src/lib/db/types.ts` is generated, never hand-edited. One narrow client type,
 * declared here and nowhere else, keeps every call site below fully typed against the row shape the
 * migration actually creates. DELETE this block (and the cast in `jobRunsDb()`) the moment types.ts
 * carries `job_runs`; nothing else in the codebase depends on it.
 */
type JobRunsDatabase = {
  public: {
    Tables: {
      job_runs: {
        Row: JobRunRow;
        Insert: JobRunInsert;
        Update: Partial<JobRunInsert>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

function jobRunsDb(): SupabaseClient<JobRunsDatabase, "public"> {
  return createAdminClient() as unknown as SupabaseClient<
    JobRunsDatabase,
    "public"
  >;
}

// ---------------------------------------------------------------------------
// Kill switches (ops_flags)
// ---------------------------------------------------------------------------

/**
 * Every job's switch state, keyed by JobId. A MISSING row reads as enabled (the flag simply has not
 * been seeded), but an unreachable table THROWS: a kill switch that fails open is not a kill switch
 * (the /admin/exports lesson, kept verbatim here).
 */
export async function getJobFlags(): Promise<Record<JobId, boolean>> {
  const admin = createAdminClient();
  const keys = JOBS.map((j) => j.flagKey);
  const rows = await mustQuery(
    admin.from("ops_flags").select("key, enabled").in("key", keys),
    "admin/jobs: kill switches",
  );
  const byKey = new Map((rows ?? []).map((r) => [r.key, r.enabled]));
  const out = {} as Record<JobId, boolean>;
  for (const job of JOBS) out[job.id] = byKey.get(job.flagKey) ?? true;
  return out;
}

/** One job's switch, for the job itself (which only cares about its own). */
export async function isJobEnabled(job: JobId): Promise<boolean> {
  const flags = await getJobFlags();
  return flags[job];
}

/** Flip one job's switch. Callers re-check admin + AAL2 first; this is the write half only. */
export async function setJobEnabled(
  flagKey: string,
  enabled: boolean,
): Promise<{ error: string | null }> {
  const admin = createAdminClient();
  // upsert, not update: a flag row the migration has not seeded yet must still be switchable rather
  // than silently updating zero rows and reporting success.
  const { error } = await admin
    .from("ops_flags")
    .upsert(
      { key: flagKey, enabled, updated_at: new Date().toISOString() },
      { onConflict: "key" },
    );
  return { error: error?.message ?? null };
}

// ---------------------------------------------------------------------------
// The heartbeat (job_runs writes — degrade, never throw)
// ---------------------------------------------------------------------------

export type StartedRun = {
  /** Null when the row could not be written; the job still runs, `heartbeatError` says why. */
  runId: string | null;
  startedAtMs: number;
  heartbeatError: string | null;
};

/** Open a `running` row. Never throws: a job must not die because its heartbeat could not be written. */
export async function startJobRun(
  job: JobId,
  triggeredBy: JobTrigger,
): Promise<StartedRun> {
  const startedAtMs = Date.now();
  try {
    const { data, error } = await jobRunsDb()
      .from("job_runs")
      .insert({
        job,
        status: "running",
        triggered_by: triggeredBy,
        started_at: new Date(startedAtMs).toISOString(),
      })
      .select("id")
      .single();
    if (error)
      return { runId: null, startedAtMs, heartbeatError: error.message };
    return { runId: data.id, startedAtMs, heartbeatError: null };
  } catch (e) {
    return { runId: null, startedAtMs, heartbeatError: String(e) };
  }
}

/** Close a run. A null `runId` (the heartbeat never opened) is a no-op, not an error. */
export async function finishJobRun(
  run: StartedRun,
  outcome: {
    status: Exclude<JobRunStatus, "running">;
    counts?: Json;
    note?: string;
  },
): Promise<{ heartbeatError: string | null }> {
  if (!run.runId) return { heartbeatError: run.heartbeatError };
  try {
    const { error } = await jobRunsDb()
      .from("job_runs")
      .update({
        status: outcome.status,
        finished_at: new Date().toISOString(),
        duration_ms: Date.now() - run.startedAtMs,
        counts: outcome.counts ?? null,
        note: outcome.note ?? null,
      })
      .eq("id", run.runId);
    return { heartbeatError: error?.message ?? null };
  } catch (e) {
    return { heartbeatError: String(e) };
  }
}

/**
 * Record a run that never happened because the job is paused. Written as a CLOSED row so a paused
 * job keeps reporting in and never trips the missed-run alert: pausing is a decision, not a fault.
 */
export async function recordSkippedRun(
  job: JobId,
  triggeredBy: JobTrigger,
  note: string,
): Promise<{ heartbeatError: string | null }> {
  try {
    const now = new Date().toISOString();
    const { error } = await jobRunsDb().from("job_runs").insert({
      job,
      status: "skipped",
      triggered_by: triggeredBy,
      started_at: now,
      finished_at: now,
      duration_ms: 0,
      note,
    });
    return { heartbeatError: error?.message ?? null };
  } catch (e) {
    return { heartbeatError: String(e) };
  }
}

// ---------------------------------------------------------------------------
// The readout (job_runs reads — mustQuery, throw loudly)
// ---------------------------------------------------------------------------

/** The newest runs across every job, for the /admin/jobs activity feed. */
export async function listRecentJobRuns(limit = 60): Promise<JobRunRow[]> {
  const rows = await mustQuery(
    jobRunsDb()
      .from("job_runs")
      .select(
        "id, job, status, triggered_by, started_at, finished_at, duration_ms, counts, note",
      )
      .order("started_at", { ascending: false })
      .limit(limit),
    "admin/jobs: recent runs",
  );
  return rows ?? [];
}

export type JobState = {
  job: JobId;
  /** The newest run of any status (what the card shows as "last run"). */
  lastRun: JobRunSummary | null;
  lastRunRow: JobRunRow | null;
  /** The newest run that actually REPORTED a result — the freshness clock. */
  lastFinishedAtMs: number | null;
};

/**
 * Per-job freshness, used by BOTH the page cards and the missed-run scan so the two can never drift
 * into different definitions of "last heard from". Two indexed single-row reads per job.
 */
export async function getJobStates(): Promise<JobState[]> {
  const db = jobRunsDb();
  return Promise.all(
    JOBS.map(async (def): Promise<JobState> => {
      const [latest, lastFinished] = await Promise.all([
        mustQuery(
          db
            .from("job_runs")
            .select(
              "id, job, status, triggered_by, started_at, finished_at, duration_ms, counts, note",
            )
            .eq("job", def.id)
            .order("started_at", { ascending: false })
            .limit(1)
            .maybeSingle(),
          `admin/jobs: latest run (${def.id})`,
        ),
        mustQuery(
          db
            .from("job_runs")
            .select("finished_at")
            .eq("job", def.id)
            .not("finished_at", "is", null)
            .order("finished_at", { ascending: false })
            .limit(1)
            .maybeSingle(),
          `admin/jobs: last finish (${def.id})`,
        ),
      ]);
      return {
        job: def.id,
        lastRunRow: latest,
        lastRun: latest
          ? {
              status: latest.status,
              startedAtMs: Date.parse(latest.started_at),
              finishedAtMs: latest.finished_at
                ? Date.parse(latest.finished_at)
                : null,
            }
          : null,
        lastFinishedAtMs: lastFinished?.finished_at
          ? Date.parse(lastFinished.finished_at)
          : null,
      };
    }),
  );
}
